version: "3.7"
services:
  # Service for the Postgres database
  # Proxies requests to internal services
  api-gateway:
    image: nginx:1.17.10
    container_name: reverse_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  frontend:
    build:
      context: ./frontend
      dockerfile: web.Dockerfile
    ports:
      - 8080:80
    restart: on-failure

#MOUNTING VOLUMES
#volumes:
