version: "3.7"
services:
  # Service for the Postgres database
  # Proxies requests to internal services
  api-gateway:
    image: nginx:1.17.10
    container_name: reverse_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  frontend:
    build:
      context: ./frontend
      dockerfile: web.Dockerfile
    ports:
      - 8080:80
    restart: on-failure
  
  databaseall:
    # Pull the latest 'postgres' image
    image: "postgres"
    container_name: ""
    # Postgres environment parameters and creating volumes to keep data saved in local
    volumes:
      - humidity-database:/var/lib/postgresql/data
      - ./db/init-humidity-database.sh:/docker-entrypoint-initdb.d/init-humidity-database.sh
    # Create environment
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD="1234"
    # Bind mount the default Postgres port
    ports:
      - 5004:5432

#MOUNTING VOLUMES
#volumes:
